In [63]:
import praw
import pandas as pd

In [66]:
reddit = praw.Reddit(
        client_id = '1RSoiiidEQHVgW7YVwlubA',
        client_secret = 'zJpONyQaL_GzTTGM9Ye-U0Mg9MI8qA',
        user_agent = 'script:my_nlp_app:v1.0 (Evie-F-2025)'
    )

In [68]:
# subreddit to scrape
subreddit = reddit.subreddit('dyson')

data = []

# scraping posts and comments
for post in subreddit.top(limit=10):
    post_data = {
        'Type' : 'post',
        'Title': post.title,
        'Time Stamp' : post.created_utc,
        'Score': post.score,
        'Id': post.id,
        'Url': post.url,
        'Num Comments': post.num_comments,
        'Post Text': post.selftext
    }
    data.append(post_data)

    if post.num_comments > 0:
        post.comments.replace_more(limit=0)
        for comment in post.comments.list():
            comment_data = {
                'Type': 'comment',
                'Post Id': post.id,
                'Comment Id': comment.id,
                'Comment Text': comment.body,
                'Score': comment.score,
                'Time Stamp': comment.created_utc
            }
            data.append(comment_data)

dyson_data = pd.DataFrame(data)
dyson_data.head()

Forbidden: received 403 HTTP response

In [60]:
# subreddit to scrape
subreddit = reddit.subreddit('sony')

data = []
# scraping posts and comments
for post in subreddit.top(limit=10): # top = filters for the highest upvoted posts within a specific time range. This is best for finding high-quality content or popular discussions.
    post_data = {
        'Type' : 'post',
        'Title': post.title,
        'Time Stamp' : post.created_utc,
        'Score': post.score,
        'Id': post.id,
        'Url': post.url,
        'Num Comments': post.num_comments,
        'Post Text': post.selftext
    }
    data.append(post_data)

    if post.num_comments > 0:
        post.comments.replace_more(limit=0)
        for comment in post.comments.list():
            comment_data = {
                'Type': 'comment',
                'Post Id': post.id,
                'Comment Id': comment.id,
                'Comment Text': comment.body,
                'Score': comment.score,
                'Time Stamp': comment.created_utc
            }
            data.append(comment_data)

sony_data = pd.DataFrame(data)
sony_data.head()

Forbidden: received 403 HTTP response

In [39]:
# appending the two dataframes together
combined_data = pd.concat([dyson_data, sony_data], ignore_index=True)
combined_data.head()

,Type,Title,Time Stamp,Score,Id,Url,Num Comments,Post Text,Post Id,Comment Id,Comment Text
0,post,Every time I empty my Dyson,1.715957e+09,1508,1cu6ycr,https://i.redd.it/yruekxjy001d1.gif,53.0,It’s like scattering Donnie’s ashes…,NaN,NaN,NaN
1,comment,NaN,1.715965e+09,16,NaN,NaN,NaN,NaN,1cu6ycr,l4h8xl0,This made me laugh so much. Thanks OP.
2,comment,NaN,1.715975e+09,13,NaN,NaN,NaN,NaN,1cu6ycr,l4i2jhb,"That’s just, like, your opinion man."
3,comment,NaN,1.715994e+09,8,NaN,NaN,NaN,NaN,1cu6ycr,l4jd6xm,Lmaooo. That was literally me with my mom's as...
4,comment,NaN,1.715960e+09,4,NaN,NaN,NaN,NaN,1cu6ycr,l4gue2u,Shut the fuck up Donnie!

In [40]:
combined_data.to_csv('reddit_data.csv', index=False)

In [42]:
# Filter by keywords in the 'Comment Text' column and 'Post Text' column

# Define keywords
keywords = ['repair',
    'waste',
    'spare parts',
    'equipment',
    'replacement',
    'broken',
    'throw away',
    'fix']


# Create a regex string: "python|web scraping|data analysis"
keyword_pattern = '|'.join(keywords)

# Filter titles (case-insensitive)
filtered_df = combined_data[combined_data['Comment Text'].str.contains(keyword_pattern, case=False, na=False) 
                             | combined_data['Post Text'].str.contains(keyword_pattern, case=False, na=False)]
filtered_df.head()

,Type,Title,Time Stamp,Score,Id,Url,Num Comments,Post Text,Post Id,Comment Id,Comment Text
7,comment,NaN,1.715981e+09,3,NaN,NaN,NaN,NaN,1cu6ycr,l4iiuua,It’s one of the gripes of bagless vacuums. I g...
43,comment,NaN,1.715999e+09,1,NaN,NaN,NaN,NaN,1cu6ycr,l4jpgj7,He fixes the plumbing?
76,comment,NaN,1.716584e+09,2,NaN,NaN,NaN,NaN,1cz9yne,l5ixz9s,"Dam, thats great, I couldn't even get 2 years ..."
92,comment,NaN,1.716555e+09,2,NaN,NaN,NaN,NaN,1cz9yne,l5gq2u8,Mine died literally a week before an extended ...
136,comment,NaN,1.716563e+09,2,NaN,NaN,NaN,NaN,1cz9yne,l5hatzj,"🤷🏻‍♂️Maybe they are taking the, don't fix what..."

In [52]:
# doing all subreddits at once

subreddits = ['dyson', 'sony', 'Hewlett_Packard', 'bosch', 'apple', 'samsung', 'Appliances']
data = []

import prawcore

for sub_name in subreddits:
    subreddit = reddit.subreddit(sub_name)
    try:
        for post in subreddit.top(limit=10):  # top = filters for the highest upvoted posts within a specific time range. This is best for finding high-quality content or popular discussions.
            post_data = {
                'Type': 'post',
                'Title': post.title,
                'Time Stamp': post.created_utc,
                'Score': post.score,
                'Id': post.id,
                'Url': post.url,
                'Num Comments': post.num_comments,
                'Post Text': post.selftext
            }
            data.append(post_data)

            if post.num_comments > 0:
                post.comments.replace_more(limit=0)
                for comment in post.comments.list():
                    comment_data = {
                        'Type': 'comment',
                        'Post Id': post.id,
                        'Comment Id': comment.id,
                        'Comment Text': comment.body,
                        'Score': comment.score,
                        'Time Stamp': comment.created_utc
                    }
                    data.append(comment_data)
    except prawcore.exceptions.Forbidden:
        print("forbidden subreddit:", sub_name)
        continue

subreddit_data = pd.DataFrame(data)
subreddit_data.head()

forbidden subreddit: dyson
forbidden subreddit: sony
forbidden subreddit: Hewlett_Packard
forbidden subreddit: bosch
forbidden subreddit: apple
forbidden subreddit: samsung
forbidden subreddit: Appliances

Empty DataFrame
Columns: []
Index: []